print("Boom Boom Paazi! First test Git+PyC+GitHUb")
print("edit check + inter connection")
print("confirm the first snapshot changes")
print("2nd check for the snapshot")
print("Github.com changes to GIT")
